version: '3.7'

services:
  postgres:
    image: postgres:alpine
    environment:
      TZ: "Asia/Jakarta"
      PGTZ: "Asia/Jakarta"
      POSTGRES_DB: alfa
      POSTGRES_PASSWORD: password
      POSTGRES_USER: alfa
      PGDATA: /var/lib/postgresql/data
    container_name: postgres
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  backend:
      build: .
      environment:
        ACCESS_SECRET: 1n14d1l1h53bu4hs3cr3t
        REFRESH_SECRET: 1n14d1l1h53bu4hs3cr3t
      ports:
          - 1318:1318
      links:
        - postgres